name: Publish to PyPI

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
   pypi-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.8.6
    
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_DEEP_SEARCH_LITE }}


        